remote_theme: rms-open-letter/minima
languages:
  - name: "Brazilian Portuguese"
    code: "pt"
  - name: "French"
    code: "fr"
  - name: "Spanish"
    code: "es"
  - name: "Turkish"
    code: "tr"
